language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install pytest pytest-cov coveralls
script:
  - python setup.py test -a -v -a --cov=multigen
after_success:
  - coveralls
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    tags: true
